Added indexing support for multiple prometheus endpoints
cloud-bulldozer/kube-burner pull request #251
Opened 2023-02-10 01:43 UTC by vishnuchalla

### Description
Added indexing support for multiple prometheus endpoints\
More context here: https://github.com/cloud-bulldozer/kube-burner/issues/245

### Feel free to suggest any changes on the below thoughts applied while implementation.
### Thoughts
* Added this feature in the `index` command with a flag `-e`.
* Keeping the existing params as it is for the backward compatability.
* Added checks to make `--metric-endpoint` and `--prometheus-url` mutually exclusive.
* Keeping flexibility to pic `start`, `end` and `metrics-profile` for each endpoint from those respective CLI flags if not specified in the YAML file.
* Indexing all the results to the same UUID.
* If tarball options is used a separate tarball is generated for each endpoint. 

### Testing

Example YAML:
```
- endpoint: https://prometheus-k8s-openshift-monitoring.apps.vchalla-test.perfscale.devcluster.openshift.com
  token: <token>
  profile: /home/vchalla/e2e-benchmarking/workloads/kube-burner/metrics-profiles/metrics.yaml
  start: 126213213
  end: 234324324

- endpoint: https://prometheus-k8s-openshift-monitoring.apps.vchalla-test.perfscale.devcluster.openshift.com
  token: <token>
  profile: /home/vchalla/e2e-benchmarking/workloads/kube-burner/metrics-profiles/metrics-ovn.yaml
```

```
[vchalla@vchalla kube-burner]$ kube-burner index -c ~/kube-burner-config.yaml --job-name=node-density-heavy -e ~/metrics-endpoints.yaml 
INFO[2023-02-09 19:19:23] 📁 Creating indexer: elastic                  
INFO[2023-02-09 19:19:24] 👽 Initializing prometheus client             
INFO[2023-02-09 19:19:24] Scraping for the prometheus entry with params - {Endpoint:https://prometheus-k8s-openshift-monitoring.apps.vchalla-test.perfscale.devcluster.openshift.com, Profile:/home/vchalla/e2e-benchmarking/workloads/kube-burner/metrics-profiles/metrics.yaml, Start:2023-02-09 18:19:23 -0500 EST, End:2023-02-09 19:19:23 -0500 EST} 
INFO[2023-02-09 19:19:24] Indexing metrics with UUID 6ac5fb8a-eca4-4381-b99c-63c1116bfeec 
INFO[2023-02-09 19:19:24] 🔍 Scraping prometheus metrics for benchmark from 2023-02-09T18:19:23-05:00 to 2023-02-09T19:19:23-05:00 
INFO[2023-02-09 19:19:27] 👽 Initializing prometheus client             
INFO[2023-02-09 19:19:27] Scraping for the prometheus entry with params - {Endpoint:https://prometheus-k8s-openshift-monitoring.apps.vchalla-test.perfscale.devcluster.openshift.com, Profile:/home/vchalla/e2e-benchmarking/workloads/kube-burner/metrics-profiles/metrics-ovn.yaml, Start:2023-02-09 18:19:23 -0500 EST, End:2023-02-09 19:19:23 -0500 EST} 
INFO[2023-02-09 19:19:27] Indexing metrics with UUID 6ac5fb8a-eca4-4381-b99c-63c1116bfeec 
INFO[2023-02-09 19:19:27] 🔍 Scraping prometheus metrics for benchmark from 2023-02-09T18:19:23-05:00 to 2023-02-09T19:19:23-05:00 
INFO[2023-02-09 19:23:06] 👋 Exiting kube-burner 6ac5fb8a-eca4-4381-b99c-63c1116bfeec 

```

2023-02-10 12:12 UTC, jtaleric commented
Nice work @vishnuchalla! Could you update the docs to call out this new enhancement? We should also add some tests.

2023-02-10 13:46 UTC, vishnuchalla commented
> Nice work @vishnuchalla! Could you update the docs to call out this new enhancement? We should also add some tests.

By tests are we referring to the unit-tests or e2e-tests?

2023-02-10 16:31 UTC, jtaleric commented
> > Nice work @vishnuchalla! Could you update the docs to call out this new enhancement? We should also add some tests.
> 
> @jtaleric By tests are we referring to the unit-tests or e2e-tests?

simple unit - https://github.com/cloud-bulldozer/kube-burner/tree/master/test 

A test that uses the old method to collect prom data, and a test for the new method.

2023-02-11 20:59 UTC, vishnuchalla commented
> > > Nice work @vishnuchalla! Could you update the docs to call out this new enhancement? We should also add some tests.
> > 
> > 
> > @jtaleric By tests are we referring to the unit-tests or e2e-tests?
> 
> simple unit - https://github.com/cloud-bulldozer/kube-burner/tree/master/test
> 
> A test that uses the old method to collect prom data, and a test for the new method.

Updated both tests and docs. Thanks.

2023-02-13 20:42 UTC, jtaleric commented
I am getting a hypershift + CVN up to kick the tires with this change.

2023-02-13 21:59 UTC, vishnuchalla commented
> I am getting a hypershift + CVN up to kick the tires with this change.

Just trying to understand. What is a CVN in this context?

2023-02-14 12:09 UTC, rsevilla87 commented on cmd/kube-burner/kube-burner.go
> +			if (metricsEndpoint != "" && url != "") || (metricsEndpoint == "" && url == "") {
You can use

```
cmd.MarkFlagsMutuallyExclusive("metrics-endpoint", "url")
```

To make these flags mutually exclusive.
```

2023-02-14 13:16 UTC, jtaleric commented
> > I am getting a hypershift + CVN up to kick the tires with this change.
> 
> Just trying to understand. What is a CVN in this context?

Sorry, CNV / Kubevirt

2023-02-14 14:16 UTC, vishnuchalla commented on cmd/kube-burner/kube-burner.go
> +			if (metricsEndpoint != "" && url != "") || (metricsEndpoint == "" && url == "") {
IMHO by simply marking them as mutually exclusive I am afraid that we might miss this case `(metricsEndpoint == "" && url == "")` wherein when none of the them are specified the metrics won't get scraped at all which might bring the purpose of `index` command into jeopardy.

2023-02-14 16:10 UTC, vishnuchalla commented
> > > I am getting a hypershift + CVN up to kick the tires with this change.
> > 
> > 
> > Just trying to understand. What is a CVN in this context?
> 
> Sorry, CNV / Kubevirt

Thank you!

2023-02-15 16:42 UTC, rsevilla87 commented on test/kube-burner-index-multiple-endpoint.yml
> +global:
What's the goal of these files on the test dir?, they are not being used at all

2023-02-15 16:43 UTC, rsevilla87 commented on test/kube-burner-index-multiple-endpoint.yml
> +global:
I can help you to introduce some tests for this feature

2023-02-15 17:29 UTC, jtaleric requested changes
We should consider allowing the user to provide the endpoints to all commands (init, ocp, index).

2023-02-15 17:29 UTC, jtaleric commented on cmd/kube-burner/kube-burner.go
> +					}
+1

2023-02-16 20:53 UTC, dry923 commented on docs/metrics.md
> +  start: 132413423
Given the start/end options are optional lets remove them from one of the examples

2023-02-20 14:44 UTC, vishnuchalla commented on cmd/kube-burner/kube-burner.go
> +					}
Moved the common pieces of code to different file and broken them into small reusable functions.

2023-02-20 14:45 UTC, vishnuchalla commented on test/kube-burner-index-multiple-endpoint.yml
> +global:
Thanks for pointing out. I have added the tests and verified their execution. Let me know if you have any concerns.

2023-02-20 14:46 UTC, vishnuchalla commented
> We should consider allowing the user to provide the endpoints to all commands (init, ocp, index).

Extended the functionality for both `ocp` and `index` commands as suggested. Thanks

2023-02-20 14:47 UTC, vishnuchalla commented on docs/metrics.md
> +  start: 132413423
Removed from one of the examples to indicate optional usage. Thanks

2023-02-20 20:14 UTC, jtaleric reviewed
Need to test locally, looks good, just one nit. Nice work @vishnuchalla!!

2023-02-20 20:14 UTC, jtaleric commented on pkg/commons/commons.go
> +		if caller == "index" {
instead of this being a string, should we just pass a bool of `index=false|true`?

2023-02-20 20:14 UTC, jtaleric commented on pkg/commons/commons.go
> +		if caller == "index" {
Or you could add to the `MetricsScraperRequest` struct? where `actionOCP, actionIndex, actionInit` as bools? However it seems we just need to distinguish between index vs init,ocp.

2023-02-20 21:16 UTC, vishnuchalla commented on pkg/commons/commons.go
> +		if caller == "index" {
Acknowledged. The initial idea was to keep a caller variable so that we can use it for distinguishing between multiple workflows using a switch case if needed to extend. But as of now since we only have two use cases, to keep it short and simple , introducing a boolean variable as `ActionIndex` in `MetricsScraperRequest` to distinguish between index vs non-index workflows.

2023-02-21 09:43 UTC, rsevilla87 commented on pkg/commons/utils.go
> +
What's the goal of this funtion?, im my opinion is redundant

2023-02-21 09:47 UTC, rsevilla87 commented on pkg/burner/job.go
> +				prometheusJobList = append(prometheusJobList, prometheusJob)
```suggestion
				prometheusClient.JobList = append(prometheusClient.JobList, prometheusJob)
```

2023-02-21 09:48 UTC, rsevilla87 commented on pkg/burner/job.go
> +			prometheusClient.JobList = prometheusJobList
Remove this line, it's already addressed in 162

2023-02-21 09:49 UTC, rsevilla87 commented on pkg/burner/job.go
> +			time.Sleep(prometheusClient.Step)
These two lines must be executed only once and not with every prometheus client on the slice.

2023-02-21 10:03 UTC, rsevilla87 commented on pkg/commons/commons.go
> +			HandleTarball(configSpec)
Why are you scraping metrics from here?

2023-02-21 10:05 UTC, rsevilla87 commented on pkg/commons/commons.go
> +			HandleTarball(configSpec)
With this logic, kube-burner will scrape metrics before running any benchmark....

2023-02-21 10:06 UTC, rsevilla87 commented on pkg/commons/commons.go
> +		ConfigSpec:        configSpec,
I think you don't need to return ConfigSpec

2023-02-21 10:07 UTC, rsevilla87 commented on pkg/commons/commons.go
> +			alertM = nil
Not needed

2023-02-21 10:12 UTC, rsevilla87 commented on pkg/commons/commons.go
> +// Copyright 2020 The Kube-burner Authors.
I don't like the "commons" name for this package, it's very generic, can you rename it to `prometheus-utils`?

2023-02-21 10:14 UTC, rsevilla87 commented on pkg/commons/commons.go
> +func ProcessMetricsScraperConfig(metricsScraperRequest MetricsScraperRequest) MetricsScraperResponse {
```suggestion
func ProcessMetricsScraperConfig(config MetricsScraperConfig) MetricsScraperResponse {
```

2023-02-21 10:21 UTC, rsevilla87 commented on pkg/workloads/helpers.go
> +	for _, eachEntry := range metricsEndpoints {
```suggestion
	for _, metricsEndpoint := range metricsEndpoints {
```

2023-02-21 10:22 UTC, rsevilla87 commented on pkg/commons/commons.go
> +	for _, eachEntry := range metricsEndpoints {
```suggestion
	for _, metricsEndpoint := range metricsEndpoints {
```

2023-02-21 10:22 UTC, rsevilla87 commented on pkg/commons/commons.go
> +	for _, eachEntry := range metricsEndpoints {
```suggestion
	for _, metricsEndpoint := range metricsEndpoints {
```

2023-02-21 10:29 UTC, rsevilla87 commented on pkg/burner/job.go
> +				log.Infof("Evaluating alerts for prometheus - %v", prometheusClient.ConfigSpec.GlobalConfig.PrometheusURL)
I think we can add the prometheus endpoint to the prometheusClient struct to reduce this long expression  (prometheusClient.ConfigSpec.GlobalConfig.PrometheusURL) to `prometheusClient.Endpoint`

2023-02-21 10:30 UTC, rsevilla87 commented on test/run-ocp.sh
> +kube-burner ocp cluster-density --iterations=1 --churn-duration=2m --metrics-endpoint metrics-endpoints.yaml ${COMMON_FLAGS}
There's no need to run tests using  the flag `--metrics-endpoint`  multiple times, only once should be enough

2023-02-21 10:39 UTC, rsevilla87 commented on pkg/commons/utils.go
> +		p.JobList[len(p.JobList)-1].End)
```suggestion
	log.Infof("Scraping for the prometheus entry with params: Endpoint: %v ;  Profile: %v ; Start:%v, End:%v",
		p.ConfigSpec.GlobalConfig.PrometheusURL,
		p.ConfigSpec.GlobalConfig.MetricsProfile,
		p.JobList[0].Start.Format(time.RFC3339),
		p.JobList[len(p.JobList)-1].End.Format(time.RFC3339))
```

2023-02-21 10:40 UTC, rsevilla87 commented on pkg/commons/utils.go
> +	log.Infof("Indexing metrics with UUID %s", p.UUID)
Remove

2023-02-21 10:48 UTC, rsevilla87 commented on test/run.sh
> +timeout 500 kube-burner init -c kube-burner.yml --uuid ${uuid} --log-level=debug -e metrics-endpoints.yaml
This test should have failed, the `metrics-ovn.yaml` file doesn't exist

2023-02-21 10:49 UTC, rsevilla87 commented on docs/cli.md
> +Note: Options `profile`, `alertProfile` are optional. If not provided will be taken from the CLI flags first or else will be populated with the default values. And also apart from valid keys rest all
```suggestion
To scrape metrics from multiple endpoints init command can be triggered as below.

```
kube-burner init -c cluster-density.yml -e metrics-endpoints.yaml
```

And a metrics-endpoints.yaml file with valid keys for the `init` command would look something like this.

```
- endpoint: http://localhost:9090
  token: <token>
  profile: metrics.yaml
  alertProfile: alert-profile.yaml
- endpoint: http://remotehost:9090
  token: <token>
```

Note: Options `profile`, `alertProfile` are optional. If not provided will be taken from the CLI flags first or else will be populated with the default values. And also apart from valid keys rest all will be ignored.
```

2023-02-21 10:50 UTC, rsevilla87 commented on docs/cli.md
> +To scrape metrics from multiple endpoints init command can be triggered as below.
Add new lines before and after a code block ```

2023-02-21 21:10 UTC, vishnuchalla commented on pkg/burner/job.go
> +				prometheusJobList = append(prometheusJobList, prometheusJob)
Here at line#162 we are adding all the jobs to the joblist at once while the jobs are being run and then using the same job list before scraping every Prometheus client in the list at line#187. If I make the suggested change we will only end up adding the job List to one Prometheus client leaving other's JobList empty (Since we have a list of prometheus clients now and each client needs to be aware of the JobList for scraping).

2023-02-21 21:10 UTC, vishnuchalla commented on pkg/burner/job.go
> +			prometheusClient.JobList = prometheusJobList
Reason same as the above comment with regards to line#162 and line#187

2023-02-21 21:10 UTC, vishnuchalla commented on pkg/burner/job.go
> +			time.Sleep(prometheusClient.Step)
Modified it as suggested. Executing only once before starting to scrape the list of endpoints.

2023-02-21 21:10 UTC, vishnuchalla commented on pkg/commons/commons.go
> +		ConfigSpec:        configSpec,
I guess we will need to return because burner.Run uses the ConfigSpec returned from this struct. For example `burner.Run(metricsScraper.ConfigSpec, uuid, metricsScraper.PrometheusClients, metricsScraper.AlertMs, metricsScraper.Indexer, timeout)`

2023-02-21 21:11 UTC, vishnuchalla commented on pkg/commons/commons.go
> +			alertM = nil
Thought this would be useful if users wants a separate alert profile for each Prometheus client. So keeping it for flexibility. Let me know if it still needs to be changed.

2023-02-21 21:11 UTC, vishnuchalla commented on pkg/commons/commons.go
> +			if eachEntry.Start == eachEntry.End {
This happens when the user forgets to specify both start and end dates and if ends up specifying a same value for both of them.

2023-02-21 21:11 UTC, vishnuchalla commented on pkg/commons/commons.go
> +// Copyright 2020 The Kube-burner Authors.
I have tried doing that but we are running into "import cycles". So In order to fix that, had to move everything into a separate package altogether.

2023-02-21 21:11 UTC, vishnuchalla commented on pkg/commons/commons.go
> +func ProcessMetricsScraperConfig(metricsScraperRequest MetricsScraperRequest) MetricsScraperResponse {
Changed it accordingly. Thanks

2023-02-21 21:11 UTC, vishnuchalla commented on pkg/workloads/helpers.go
> +	for _, eachEntry := range metricsEndpoints {
Done. Changed as suggested.

2023-02-21 21:11 UTC, vishnuchalla commented on pkg/commons/commons.go
> +	for _, eachEntry := range metricsEndpoints {
Changed as suggested.

2023-02-21 21:11 UTC, vishnuchalla commented on pkg/burner/job.go
> +				log.Infof("Evaluating alerts for prometheus - %v", prometheusClient.ConfigSpec.GlobalConfig.PrometheusURL)
Yes, modified as suggested to remove the long variable.

2023-02-21 21:11 UTC, vishnuchalla commented on test/run-ocp.sh
> +kube-burner ocp cluster-density --iterations=1 --churn-duration=2m --metrics-endpoint metrics-endpoints.yaml ${COMMON_FLAGS}
Sure. Keeping only one test for this flag running `cluster-density`. Thanks

2023-02-21 21:11 UTC, vishnuchalla commented on pkg/commons/utils.go
> +		p.JobList[len(p.JobList)-1].End)
Changed as suggested. Thank you.

2023-02-21 21:11 UTC, vishnuchalla commented on pkg/commons/utils.go
> +	log.Infof("Indexing metrics with UUID %s", p.UUID)
Removed the long variable for Endpoint. Thank you.

2023-02-21 21:11 UTC, vishnuchalla commented on test/run.sh
> +timeout 500 kube-burner init -c kube-burner.yml --uuid ${uuid} --log-level=debug -e metrics-endpoints.yaml
It was due to the early exit${rc} in the previous test. This test did not even get executed. Fixed and updated the code. Thanks for pointing it out.

2023-02-21 21:11 UTC, vishnuchalla commented on docs/cli.md
> +To scrape metrics from multiple endpoints init command can be triggered as below.
Done. Changed as suggested.

2023-02-27 15:34 UTC, rsevilla87 commented on pkg/commons/utils.go
> +	log.Infof("Scraping for the prometheus entry with params - {Endpoint:%v, Profile:%v, Start:%v, End:%v}\n",
Minor nit you remove \n?
Just seen this line in the log

```
time="2023-02-21 22:42:16" level=info msg="Scraping for the prometheus entry with params - {Endpoint:https://prometheus-k8s-openshift-monitoring.apps.cloud-bulldozer-ci.perfscale.devcluster.openshift.com/, Profile:metrics.yml, Start:2023-02-21T22:41:27Z, End:2023-02-21T22:41:44Z}\n"
```

2023-02-27 15:36 UTC, rsevilla87 commented on test/run.sh
> +timeout 500 kube-burner init -c kube-burner.yml --uuid ${uuid} --log-level=debug -e metrics-endpoints.yaml
nice

2023-02-27 15:42 UTC, rsevilla87 commented on pkg/burner/job.go
> +				prometheusJobList = append(prometheusJobList, prometheusJob)
gotcha, thanks!

2023-02-27 15:43 UTC, rsevilla87 commented on pkg/commons/commons.go
> +		ConfigSpec:        configSpec,
ok

2023-02-27 15:53 UTC, rsevilla87 commented on pkg/commons/commons.go
> +			if eachEntry.Start == eachEntry.End {
But, why these two lines are necessary?
```
				eachEntry.Start = metricsScraperRequest.StartTime
				eachEntry.End = metricsScraperRequest.EndTime
```

Also, that condition shouldn't happen, look at the defaults

https://github.com/cloud-bulldozer/kube-burner/blob/9bac81763e5f1808b9bc24c61d8a31ec33c6d8d7/cmd/kube-burner/kube-burner.go#L274-L275


They always take a value, and the start value is 1 hour less than End

2023-02-27 18:44 UTC, vishnuchalla commented on pkg/commons/utils.go
> +	log.Infof("Scraping for the prometheus entry with params - {Endpoint:%v, Profile:%v, Start:%v, End:%v}\n",
Thanks for pointing out. Changed as suggested.

2023-02-27 18:44 UTC, vishnuchalla commented on pkg/commons/commons.go
> +			if eachEntry.Start == eachEntry.End {
Yes Agreed with the CLI logic. But in the above condition, the ones with `eachEntry.Start` and `eachEntry.End` are referring to the start and end dates from the yaml input for each entry (which are now modified as `metricsEndpoint.Start` and `metricsEndpoint.End` as per previous suggestions) and `mertricsScraperConfig.StartTime` and `metricsScraperConfig.EndTime` are referring to the values specified through CLI. So the command line args will any how get populated with the default values if not specified. The above condition focuses on safely setting the values of start and end times read from the yaml. i.e It checks if something is wrong with the inputs provided from yaml it sets the values read from CLI or the default values as you mentioned. With that said the invalid assignments from YAML are check for below cases.
* Only when start date is specified.
* Only when end date is specified.
* When both start and end dates are not specified.
* When both start and end dates are same.    

Please feel free to let me know if my explanation above is unclear. We discuss in detail over a call. Thanks

2023-02-28 08:37 UTC, rsevilla87 commented on pkg/commons/commons.go
> +			if eachEntry.Start == eachEntry.End {
oh, didn't realize that the user could pass start/end dates from the yaml file as well, I personally I don't see the point of that, anyway, it doesn't harm anything.

2023-02-28 08:37 UTC, rsevilla87 commented
@vishnuchalla, seems like this one needs some rebase before merging

2023-02-28 13:14 UTC, vishnuchalla commented on pkg/commons/commons.go
> +			if eachEntry.Start == eachEntry.End {
Just an extra flexibility to the user while indexing from multiple endpoints :)

2023-02-28 21:34 UTC, merged