integrating go-commons prometheus
cloud-bulldozer/kube-burner pull request #317
Opened 2023-05-19 17:34 UTC by vishnuchalla

### Description

### Fixes

2023-05-30 20:12 UTC, rsevilla87 requested changes
Hi!, I added some comments

2023-05-30 20:12 UTC, rsevilla87 commented on pkg/prometheus/prometheus.go
> -				jobConfig.Objects = nil         // no need to insert this into the metric
I see no reference to these 2 lines in createMetric()

2023-05-31 17:37 UTC, vishnuchalla commented on pkg/prometheus/prometheus.go
> -				jobConfig.Objects = nil         // no need to insert this into the metric
Yes. As mentioned above, by default their value will be nil, so did not set them.

2023-05-31 17:37 UTC, vishnuchalla commented on pkg/prometheus/prometheus.go
> +		JobName:    jobName,
Changed as suggested.

2023-05-31 17:37 UTC, vishnuchalla commented on pkg/util/metrics/utils.go
> +	"github.com/vishnuchalla/go-commons/indexers"
Its just go formatting. Will be fixed when used the right import.

2023-05-31 17:37 UTC, vishnuchalla commented on pkg/prometheus/prometheus.go
> -					jobConfig.Objects = nil         // no need to insert this into the metric.
Yes. By default their value will be nil, so did not set them.

2023-05-31 18:01 UTC, vishnuchalla commented on pkg/prometheus/prometheus.go
> +func createMetric(uuid, query, metricName, jobName string, jobConfig config.Job, metadata map[string]interface{}, labels model.Metric, value model.SampleValue, timestamp time.Time) metric {
Changed as suggested, which reduced some amount of arguments.

2023-05-31 22:08 UTC, rsevilla87 commented
> Regarding the queries on `ClusterMetadata`, had to make that change to fix golangci-lint errors as below. Please feel free to let me know if you have any other thoughts on this. Thanks!
> 
> ```
> pkg/workloads/helpers.go:41:2: undefined: ocpmetadata (typecheck)
> 	ocpmetadata.ClusterMetadata
> 	^
> pkg/workloads/helpers.go:133:27: wh.Metadata.MetricName undefined (type BenchmarkMetadata has no field or method MetricName) (typecheck)
> 		MetricName: wh.Metadata.MetricName,
> 		                        ^
> pkg/workloads/helpers.go:145:29: wh.Metadata.Platform undefined (type BenchmarkMetadata has no field or method Platform) (typecheck)
> 		"platform":   wh.Metadata.Platform,
> 		                          ^
> pkg/workloads/helpers.go:146:29: wh.Metadata.OCPVersion undefined (type BenchmarkMetadata has no field or method OCPVersion) (typecheck)
> 		"ocpVersion": wh.Metadata.OCPVersion,
> 		                          ^
> pkg/workloads/helpers.go:147:29: wh.Metadata.K8SVersion undefined (type BenchmarkMetadata has no field or method K8SVersion) (typecheck)
> 		"k8sVersion": wh.Metadata.K8SVersion,
> 		                          ^
> pkg/workloads/helpers.go:148:29: wh.Metadata.TotalNodes undefined (type BenchmarkMetadata has no field or method TotalNodes) (typecheck)
> 		"totalNodes": wh.Metadata.TotalNodes,
> 		                          ^
> pkg/workloads/helpers.go:149:29: wh.Metadata.SDNType undefined (type BenchmarkMetadata has no field or method SDNType) (typecheck)
> 		"sdnType":    wh.Metadata.SDNType,
> ```

Somethis is not working well, I don't see any indexed document in ElasticSearch from the OCP wrapper tests.

2023-05-31 22:08 UTC, rsevilla87 commented on pkg/workloads/helpers.go
> +	ClusterMetadata ocpmetadata.ClusterMetadata
It was passing linters before this PR

2023-06-01 13:12 UTC, vishnuchalla commented
> > Regarding the queries on `ClusterMetadata`, had to make that change to fix golangci-lint errors as below. Please feel free to let me know if you have any other thoughts on this. Thanks!
> > ```
> > pkg/workloads/helpers.go:41:2: undefined: ocpmetadata (typecheck)
> > 	ocpmetadata.ClusterMetadata
> > 	^
> > pkg/workloads/helpers.go:133:27: wh.Metadata.MetricName undefined (type BenchmarkMetadata has no field or method MetricName) (typecheck)
> > 		MetricName: wh.Metadata.MetricName,
> > 		                        ^
> > pkg/workloads/helpers.go:145:29: wh.Metadata.Platform undefined (type BenchmarkMetadata has no field or method Platform) (typecheck)
> > 		"platform":   wh.Metadata.Platform,
> > 		                          ^
> > pkg/workloads/helpers.go:146:29: wh.Metadata.OCPVersion undefined (type BenchmarkMetadata has no field or method OCPVersion) (typecheck)
> > 		"ocpVersion": wh.Metadata.OCPVersion,
> > 		                          ^
> > pkg/workloads/helpers.go:147:29: wh.Metadata.K8SVersion undefined (type BenchmarkMetadata has no field or method K8SVersion) (typecheck)
> > 		"k8sVersion": wh.Metadata.K8SVersion,
> > 		                          ^
> > pkg/workloads/helpers.go:148:29: wh.Metadata.TotalNodes undefined (type BenchmarkMetadata has no field or method TotalNodes) (typecheck)
> > 		"totalNodes": wh.Metadata.TotalNodes,
> > 		                          ^
> > pkg/workloads/helpers.go:149:29: wh.Metadata.SDNType undefined (type BenchmarkMetadata has no field or method SDNType) (typecheck)
> > 		"sdnType":    wh.Metadata.SDNType,
> > ```
> 
> Something is not working well, I don't see any indexed document in ElasticSearch from the OCP wrapper tests.

@rsevilla87  It was not realted to the changes in this PR. The root cause for no indexing in ocp tests was an incorrect declaration and usage of a [variable](https://github.com/cloud-bulldozer/kube-burner/blob/master/test/run-ocp.sh#L19) in our test script, which was introduced in one of our old [PRs](https://github.com/cloud-bulldozer/kube-burner/pull/318) as a part of correcting lint errors. Now with the new fix in the script we are able to see the index functionality working. And also I feel like having `ClusterMetadata` a name will make it more verbose and help the devs understand on where the variable is coming from rather than embedding it. But, happy to keep it embedded if we still want it. Thanks!

2023-06-02 08:44 UTC, rsevilla87 commented on pkg/prometheus/prometheus.go
> -					jobConfig.Objects = nil         // no need to insert this into the metric.
Their value is not nil, I've seen documents indexed with these fields and we wanted to remove them.

2023-06-02 09:20 UTC, rsevilla87 commented
> lso I feel like having `ClusterMetadata` a name will make it more verbose and help the devs understand on where the varia

The field ClusterMetadata must be embed, assigning a field name to it would generate a different document and making it not backwards compatible. e.g.

This is what's being generated now with this PR:

```json
[
  {
    "ClusterMetadata": {
      "metricName": "clusterMetadata",
      "platform": "AWS",
      "ocpVersion": "4.11.17",
      "k8sVersion": "v1.24.6+5658434",
      "masterNodesType": "m5.2xlarge",
      "workerNodesType": "m5.2xlarge",
      "masterNodesCount": 3,
      "infraNodesType": "",
      "workerNodesCount": 3,
      "infraNodesCount": 0,
      "totalNodes": 3,
      "sdnType": "OpenShiftSDN",
      "clusterName": "cloud-bulldozer-ci-6hwqr",
      "region": "us-west-2"
    },
    "uuid": "4a23d767-858a-45b2-9e45-bd545f75a648",
    "benchmark": "cluster-density",
    "timestamp": "2023-06-02T09:16:55.070561012Z",
    "endDate": "2023-06-02T09:18:17.244139437Z",
    "passed": true
  }
]
```


And this is what it was being generated originally:

```json
{
    "metricName": "clusterMetadata",
    "platform": "AWS",
    "ocpVersion": "4.11.17",
    "k8sVersion": "v1.24.6+5658434",
    "masterNodesType": "m5.2xlarge",
    "workerNodesType": "m5.2xlarge",
    "masterNodesCount": 3,
    "infraNodesType": "",
    "workerNodesCount": 3,
    "infraNodesCount": 0,
    "totalNodes": 3,
    "sdnType": "OpenShiftSDN",
    "clusterName": "cloud-bulldozer-ci-6hwqr",
    "region": "us-west-2",
    "uuid": "4a75b932-bfc3-4e7c-b63d-43ad37723bd9",
    "benchmark": "cluster-density",
    "timestamp": "2023-05-17T13:45:06.663792925Z",
    "endDate": "2023-05-17T13:45:08.688147752Z",
    "passed": false
  }
```

2023-06-02 09:21 UTC, rsevilla87 commented on pkg/prometheus/prometheus.go
> -					jobConfig.Objects = nil         // no need to insert this into the metric.
```json
$ cat collected-metrics/etcdVersion.json  | jq .
[                        
  {                          
    "timestamp": "2023-06-02T11:17:59.396+02:00",
    "labels": {            
      "cluster_version": "3.5"
    },   
    "value": 3,                             
    "uuid": "4a23d767-858a-45b2-9e45-bd545f75a648",
    "query": "sum by (cluster_version)(etcd_cluster_version)",
    "metricName": "etcdVersion",
    "jobName": "cluster-density",
    "jobConfig": {
      "jobIterations": 2,
      "name": "cluster-density",
      "objects": [
        {         
          "objectTemplate": "imagestream.yml",
          "replicas": 1,               
          "namespaced": true, 
          "wait": true,        
          "waitOptions": {}
        },                         
        {                         
etc.
```

we don't want to index arbitrary fields like objects and namespaceLabels

2023-06-02 12:42 UTC, vishnuchalla commented on pkg/prometheus/prometheus.go
> -					jobConfig.Objects = nil         // no need to insert this into the metric.
Understood the context and changed as suggested. Thanks!

2023-06-02 12:42 UTC, vishnuchalla commented
> > lso I feel like having `ClusterMetadata` a name will make it more verbose and help the devs understand on where the varia
> 
> The field ClusterMetadata must be embed, assigning a field name to it would generate a different document and making it not backwards compatible. e.g.
> 
> This is what's being generated now with this PR:
> 
> ```json
> [
>   {
>     "ClusterMetadata": {
>       "metricName": "clusterMetadata",
>       "platform": "AWS",
>       "ocpVersion": "4.11.17",
>       "k8sVersion": "v1.24.6+5658434",
>       "masterNodesType": "m5.2xlarge",
>       "workerNodesType": "m5.2xlarge",
>       "masterNodesCount": 3,
>       "infraNodesType": "",
>       "workerNodesCount": 3,
>       "infraNodesCount": 0,
>       "totalNodes": 3,
>       "sdnType": "OpenShiftSDN",
>       "clusterName": "cloud-bulldozer-ci-6hwqr",
>       "region": "us-west-2"
>     },
>     "uuid": "4a23d767-858a-45b2-9e45-bd545f75a648",
>     "benchmark": "cluster-density",
>     "timestamp": "2023-06-02T09:16:55.070561012Z",
>     "endDate": "2023-06-02T09:18:17.244139437Z",
>     "passed": true
>   }
> ]
> ```
> 
> And this is what it was being generated originally:
> 
> ```json
> {
>     "metricName": "clusterMetadata",
>     "platform": "AWS",
>     "ocpVersion": "4.11.17",
>     "k8sVersion": "v1.24.6+5658434",
>     "masterNodesType": "m5.2xlarge",
>     "workerNodesType": "m5.2xlarge",
>     "masterNodesCount": 3,
>     "infraNodesType": "",
>     "workerNodesCount": 3,
>     "infraNodesCount": 0,
>     "totalNodes": 3,
>     "sdnType": "OpenShiftSDN",
>     "clusterName": "cloud-bulldozer-ci-6hwqr",
>     "region": "us-west-2",
>     "uuid": "4a75b932-bfc3-4e7c-b63d-43ad37723bd9",
>     "benchmark": "cluster-density",
>     "timestamp": "2023-05-17T13:45:06.663792925Z",
>     "endDate": "2023-05-17T13:45:08.688147752Z",
>     "passed": false
>   }
> ```

Changed as suggested.

2023-06-02 13:50 UTC, rsevilla87 approved these changes
lgtm

2023-06-02 13:51 UTC, merged