Update CI to run different workloads for commit/PR/release
cloud-bulldozer/kube-burner pull request #336
Opened 2023-06-02 14:36 UTC by morenod

Commit example: https://github.com/morenod/kube-burner/actions/runs/5156181231
PR example: https://github.com/morenod/kube-burner/pull/7
PR workload: https://github.com/morenod/kube-burner/actions/runs/5156204266
Release example: https://github.com/morenod/kube-burner/releases/tag/4.2.0
Release workload: https://github.com/morenod/kube-burner/actions/runs/5156556435

Docs Example: https://morenod.github.io/kube-burner/4.2.0/
Quay Images: https://quay.io/repository/morenod/kube-burner?tab=tags

2023-06-02 14:52 UTC, rsevilla87 commented on test/test-ocp.bats
> +  run timeout 600 kube-burner ocp cluster-density --iterations=1 --churn-duration=5m "${COMMON_FLAGS}" --timeout=1s
I think we can remove this timeout

2023-06-02 15:10 UTC, rsevilla87 commented on mkdocs.yml
> +          format: !!python/name:pymdownx.superfences.fence_code_format
dupe, it's already declared below

2023-06-02 15:16 UTC, morenod commented on mkdocs.yml
> +          format: !!python/name:pymdownx.superfences.fence_code_format
deleted

2023-06-05 22:29 UTC, rsevilla87 commented on .github/workflows/builders.yml
> +        ref: ${{ github.event.pull_request.head.sha }}
```suggestion
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.sha }}
        persist-credentials: false
```

According to docs: The auth token is persisted in the local git config. This enables your scripts to run authenticated git commands. The token is removed during post-job cleanup. Set persist-credentials: false to opt-out.

2023-06-06 09:05 UTC, rsevilla87 commented on .github/workflows/test-k8s.yml
> +      uses: redhat-actions/oc-installer@v1
Do we need to install oc in this workflow?

2023-06-06 09:25 UTC, rsevilla87 commented on test/test-k8s.bats
> +@test "Running kube-burner init: indexing on. pod latency mtrics and alert" {
```suggestion
@test "Running kube-burner init: indexing, pod latency metrics and alerting" {
```

2023-06-06 09:25 UTC, rsevilla87 commented on test/test-k8s.bats
> +@test "Running kube-burner init: indexing on. multiple endopoints" {
```suggestion
@test "Running kube-burner init: indexing and metrics-endpoint" {
```

2023-06-06 09:26 UTC, rsevilla87 commented on test/test-k8s.bats
> +@test "Running kube-burner: no indexing" {
Can we remove the "Running" prefix from the different testcases?

2023-06-06 09:26 UTC, rsevilla87 commented on test/test-k8s.bats
> +@test "Running kube-burner index: test with single prometheus endpoint" {
```suggestion
@test "Running kube-burner index: metrics-endpoints with single prometheus endpoint" {
```

2023-06-06 09:29 UTC, rsevilla87 commented on test/test-ocp.bats
> +  export BURST=2
Not used

2023-06-06 09:30 UTC, rsevilla87 commented on test/test-ocp.bats
> +  export BURST=2
Not used

2023-06-06 09:32 UTC, rsevilla87 commented on test/test-ocp.bats
> +@test "Running cluster-density wrapper and user metadata with indexing" {
```suggestion
@test "cluster-density with user metadata and indexing" {
```

2023-06-06 09:33 UTC, rsevilla87 commented on test/test-ocp.bats
> +  # Disable gc and avoid metric indexing
```suggestion
@test "node-density-cni wrapper with gc=false and no indexing" {
```

2023-06-06 09:37 UTC, rsevilla87 requested changes
Added some comments,

2023-06-06 09:46 UTC, morenod commented on .github/workflows/builders.yml
> +        ref: ${{ github.event.pull_request.head.sha }}
fixed

2023-06-06 09:46 UTC, morenod commented on .github/workflows/test-k8s.yml
> +      uses: redhat-actions/oc-installer@v1
it was required by an oc command on the tear down, so moved that command to kubectl and removed the step of installing oc

2023-06-06 09:47 UTC, morenod commented on test/test-k8s.bats
> +@test "Running kube-burner init: indexing on. pod latency mtrics and alert" {
done

2023-06-06 09:48 UTC, morenod commented on test/test-k8s.bats
> +@test "Running kube-burner init: indexing on. multiple endopoints" {
done

2023-06-06 09:48 UTC, morenod commented on test/test-k8s.bats
> +@test "Running kube-burner: no indexing" {
done

2023-06-06 09:50 UTC, morenod commented on test/test-ocp.bats
> +  run kube-burner ocp node-density-heavy --pods-per-node=75 "${COMMON_FLAGS}" --qps=5 --burst=5
done

2023-06-06 09:51 UTC, morenod commented on test/test-ocp.bats
> +  export BURST=2
removed

2023-06-06 09:52 UTC, morenod commented on test/test-ocp.bats
> +@test "Running cluster-density wrapper and user metadata with indexing" {
done

2023-06-06 09:53 UTC, morenod commented on test/test-ocp.bats
> +  # Disable gc and avoid metric indexing
done

2023-06-06 10:03 UTC, rsevilla87 approved these changes
LGTM, good stuff @morenod !

2023-06-06 10:28 UTC, vishnuchalla approved these changes
Great work. Looks good to me.

2023-06-06 10:54 UTC, merged