Support cluster scoped resources broadly
cloud-bulldozer/kube-burner pull request #341
Opened 2023-06-05 14:44 UTC by darkmuggle

As a follow on to https://github.com/cloud-bulldozer/kube-burner/pull/338, delete and patch jobs assume that the object is namespaced.
The RFE https://github.com/cloud-bulldozer/kube-burner/issues/340 suggests using the Rest Mapper to deterine the scope.

Changes:
- added a `isNamespaced` helper to determine if the GVR is namespaced or and cache schema
- updated patch.go and delete.go to check if an object is namespaced and use the appopriate
  method.

Fixes https://github.com/cloud-bulldozer/kube-burner/issues/340

2023-06-05 19:36 UTC, rsevilla87 requested changes
Thanks for the update!, I'm missing to add the isNamespaced conditional to create.go so we can take advantage of this function and remove some unnecessary logic.

i.e:
https://github.com/cloud-bulldozer/kube-burner/blob/72e9bad78db7e2412597e6ec1e8785fef7d8c58d/pkg/burner/create.go#L238-L247

Also, once we remove all references to obj.Namespaced, can you remove the references to field from the documentation?

2023-06-05 20:58 UTC, darkmuggle commented
> Thanks for the update!, I'm missing to add the isNamespaced conditional to create.go so we can take advantage of this function and remove some unnecessary logic.

Good catch. I've reputed an update with this fixed up.

> Also, once we remove all references to obj.Namespaced, can you remove the references to field from the documentation?

Done

2023-06-06 23:33 UTC, rsevilla87 commented
Hey @darkmuggle, we recently merged some heavy changes on the CI, can you rebase the PR please?

2023-06-07 18:35 UTC, rsevilla87 commented on pkg/burner/patch.go
> +	if isNamespaced(obj.gvr) {
Same as above

2023-06-07 18:39 UTC, rsevilla87 requested changes
I think we can add a `namespaced` field the the obj struct and use it, rather than perform a call to isNamespaced whenever we need to check if an object is namespace

https://github.com/cloud-bulldozer/kube-burner/blob/e280b6d4a83ec51ac361c0339d624f8c77f28ca1/pkg/burner/job.go#L40-L47

Doing that call, as is now, is a bunch of API queries, b/c most of these operations run in concurrent goroutines.

2023-06-08 19:23 UTC, darkmuggle commented on pkg/burner/create.go
> +	namespaced := isNamespaced(gvr)
> I think we can add a `namespaced` field the the obj struct and use it, rather than perform a call to isNamespaced whenever we need to check if an object is namespace

Rather than add a `namespaces` field, the last push evaluates whether the GVK is namespaced or root scoped and sets `Namespaced` to `false` if root scoped. `Namespaced` comes with the embedded struct for free. Having both a `namespaced` and `Namespaced` seemed redundant. 

The thing I don't like about this approach is that a user could create an object definition that is namespaced with a cluster GVK and erroring on it would be more correct; however the assumption is that objects are namespaced by default so it didn't seem bad.

2023-06-13 07:52 UTC, rsevilla87 commented on pkg/burner/create.go
> +				}
I think this is breaking the tests

2023-06-13 07:58 UTC, rsevilla87 commented on pkg/burner/create.go
> +				createRequest(obj.gvr, n, newObject)
If the object is namespaced... why are you passing an empty string as namespace rather than ns?
The conditional should negate obj.Namespaced

```suggestion
			go func(n string) {
				if ! obj.Namespaced {
					n = ""
				}
				createRequest(obj.gvr, n, newObject)
```

2023-06-13 08:01 UTC, rsevilla87 commented
> > Doing that call, as is now, is a bunch of API queries, b/c most of these operations run in concurrent goroutines.
> 
> > I think we can add a `namespaced` field the the obj struct and use it, rather than perform a call to isNamespaced whenever we need to check if an object is namespace
> 
> Rather than add a `namespaces` field, the last push evaluates whether the GVK is namespaced or root scoped and sets `Namespaced` to `false` if root scoped. `Namespaced` comes with the embedded struct for free. Having both a `namespaced` and `Namespaced` seemed redundant.
> 
> The thing I don't like about this approach is that a user could create an object definition that is namespaced with a cluster GVK and erroring on it would be more correct; however the assumption is that objects are namespaced by default so it didn't seem bad.

I like the new approach :), it determines if an object is namespaced in the setup stage of each type of job, nice, that won't alter the workload's outcome.
I just sent you a suggestion to fix the current issues. (you can see them in the test outputs).

2023-06-19 09:06 UTC, rsevilla87 approved these changes
lgtm

2023-06-19 09:07 UTC, merged