Add iterations-per-namespace as cli option
cloud-bulldozer/kube-burner pull request #362
Opened 2023-06-26 15:21 UTC by venkataanil

1) The current implementation has a fixed value of 1000 for iterationsPerNamespace. This patch introduces a command-line option to allow the user to specify this value. If the user doesn't provide a value, the default value will be taken from the job_iterations parameter, maintaining the behavior of creating all pods in a single namespace as before.

2) In the current implementation, one less iteration than iterationsPerNamespace is created in each namespace. For example, when iterationsPerNamespace is set to 1000, only 999 iterations are created in a namespace. This patch resolves this issue and ensures that the correct number of iterations is created.

3) iterationsPerNamespace is added node-density workload as well

## Type of change

- [ ] Refactor
- [ ] New feature
- [ ] Bug fix
- [ ] Optimization
- [ ] Documentation Update

## Description

## Related Tickets & Documents

- Related Issue #
- Closes #

## Checklist before requesting a review

- [ ] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.

2023-06-27 08:56 UTC, rsevilla87 commented on pkg/burner/create.go
> +	}
This change is breaking some workloads, since the namespace count starts with 0 rather than 1 as it was before, ie:

```
$ oc get ns                            
NAME                                               STATUS   AGE   
cluster-density-v2-0                               Active   13m   
cluster-density-v2-1                               Active   13m 
``

2023-06-27 08:58 UTC, rsevilla87 commented on pkg/burner/create.go
> +	}
This is relevant because the template variable `{{.Iteration}}` must match the namespace index and now is different

2023-06-27 09:02 UTC, rsevilla87 commented on cmd/kube-burner/ocp-config/node-density/node-density.yml
> +    namespacedIterations: true
Do we have a team agreement on this change? cc: @dry923 @jtaleric @mukrishn

2023-06-27 09:50 UTC, rsevilla87 commented on pkg/burner/create.go
> +	}
I realized that the same was happening in node-density-heavy workloads before this patch, but it wasn't affecting the workloads b/c the {{.Iteration}} variable is not used.

2023-06-27 12:26 UTC, mukrishn commented on cmd/kube-burner/ocp-config/node-density/node-density.yml
> +    namespacedIterations: true
I have never had any problem running node-density before but I'm good with this. 
Trying to find the namespace limit(if any) per cluster.

2023-06-27 19:46 UTC, paigerube14 commented on cmd/kube-burner/ocp-config/node-density/node-density.yml
> +    namespacedIterations: true
Can we make this configurable? Is there a case where we would want to run both namespacedIterations=true and namespacedIterations=false versions ?

2023-06-29 14:28 UTC, rsevilla87 commented on cmd/kube-burner/ocp-config/node-density/node-density.yml
> +    namespacedIterations: true
This is already possible by extracting the workload and customizing it. https://cloud-bulldozer.github.io/kube-burner/v1.7.1/ocp/#customizing-workloads

2023-06-29 14:28 UTC, rsevilla87 commented on cmd/kube-burner/ocp-config/node-density/node-density.yml
> +    namespacedIterations: true
Also, I don't think we should touch the current node-density workload

2023-07-04 03:34 UTC, vishnuchalla approved these changes
lgtm except for the existing comments.

2023-07-04 03:40 UTC, vishnuchalla commented on pkg/burner/create.go
> +	}
@venkataanil why did we make changes to the namespace index calculation logic? while the previous code was stable: https://github.com/cloud-bulldozer/kube-burner/pull/299

2023-07-04 13:49 UTC, vishnuchalla commented on pkg/burner/create.go
> +	}
Looks like the namespace index issue got fixed in this PR: https://github.com/cloud-bulldozer/kube-burner/pull/364. Tested and verified the change. Thank you!

2023-07-05 09:59 UTC, venkataanil commented on cmd/kube-burner/ocp-config/node-density/node-density.yml
> +    namespacedIterations: true
I want this to be consistent across all node-density variants. With this change, namespacedIterations can be used in all node-density workloads. 

namespacedIterations=false is nothing but using single namespace for all iterations which can be achieved by not setting a value of iterationsPerNamespace (i.e as explained in commit message, if the user doesn't provide a value, the default value will be taken from the job_iterations parameter, maintaining the behavior of creating all pods in a single namespace as before.)

For example, "kube-burner ocp node-density" command will create all pods in a single namespace.

2023-07-05 09:59 UTC, venkataanil commented on cmd/kube-burner/ocp-config/node-density/node-density.yml
> +    namespacedIterations: true
Please check my above comment for namespacedIterations=false and also why are touching node-desnity workload. "kube-burner ocp node-density" command will create all pods in a single namespace i.e current behaviour, with this patch.

2023-07-05 09:59 UTC, venkataanil commented on pkg/burner/create.go
> +	}
I ran node-density-cni and observed index starting at 1 while pushing this patch (i.e before PR https://github.com/cloud-bulldozer/kube-burner/pull/364 ) Please see 
https://github.com/cloud-bulldozer/kube-burner/pull/364/commits/1df75b14e13f17b448217c34eccd340091251df7#diff-bc606f2fd54d740859086073970bd68ea15b70016af24d3ac7a446741932b1edL124

 So when the index starts at 1, "iterationsPerNamespace" implementation in #299  creates one less iteration than what user has asked in iterationsPerNamespace. For example, when iterationsPerNamespace is set to 1000, only 999 iterations (starting from 1 to 999) are created in a namespace instead of 1000 iterations. This patch resolves this issue and ensures that the correct number of iterations is created i.e 1000 iterations.

Another scenario is when user doesn't provide iterationsPerNamespace, we want to create all the iterations in a single namespace. Existing implementation is creating them in 2 namespaces as iterations are starting from 1.

I will retest this patch as all workloads start from iteration 0 now because of #364

2023-07-06 18:29 UTC, vishnuchalla commented on pkg/burner/create.go
> +	}
Understood. Thanks for the detailed explanation @venkataanil .

2023-07-06 18:40 UTC, afcollins commented
While you are adding CLI arguments, would you please also add one for namespacedIterations? "editing the config" isn't a good response for changing the default because it is more complicated to script. If you are introducing one for iterationsPerNamespace, it makes sense to also add one for the other related config.

2023-07-07 11:19 UTC, rsevilla87 commented on pkg/burner/create.go
> +	}
I think these lines are not required anymore because of #364 , can you verify it @venkataanil ?

2023-07-10 12:51 UTC, jtaleric approved these changes
lgtm, shouldn't break current functionality

2023-07-10 14:27 UTC, afcollins requested changes
Commit message still says it updates node-density. Amend the commit to keep it accurate, and LGTM

2023-07-12 09:10 UTC, merged