add multus metrics
cloud-bulldozer/kube-burner pull request #472
Opened 2023-09-22 15:45 UTC by venkataanil

Recently we have seen regression in pod ready latency because of changes in multus code. CPU & memory usage of multus daemon increased while addressing this latency issue which resulted in more PRs.
We got a explict request from OVN team to track multus daemon metrics.

2023-09-22 15:50 UTC, afcollins commented on cmd/kube-burner/ocp-config/metrics-report.yml
> +  #
Delete this line pls.

2023-09-22 15:57 UTC, krishvoor commented on cmd/kube-burner/ocp-config/metrics-report.yml
> +  #
Anil please delete this minor nit otherwise, this looks good!

2023-09-22 15:58 UTC, krishvoor requested changes
A minor nit, please delete it otherwise lgtm

2023-09-25 06:32 UTC, venkataanil commented on cmd/kube-burner/ocp-config/metrics-report.yml
> +  #
sure, thanks

2023-09-25 06:33 UTC, krishvoor approved these changes
/lgtm

2023-09-25 09:04 UTC, rsevilla87 approved these changes
lgtm

2023-09-25 10:12 UTC, merged