Adding instantJobStart feature
cloud-bulldozer/kube-burner pull request #483
Opened 2023-10-03 10:17 UTC by rsevilla87

## Type of change

- [ ] Refactor
- [x] New feature
- [ ] Bug fix
- [ ] Optimization
- [ ] Documentation Update

## Description

Adding `instantJobStart` so we can fetch the first datapoint of a timeseries during a job.

## Related Tickets & Documents

- Related Issue #
- Closes #

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [x] If it is a core feature, I have added thorough tests.

2023-10-03 12:18 UTC, vishnuchalla commented
This extra configuration is not required as we can achieve the same in the rewamp logic: https://github.com/cloud-bulldozer/kube-burner/pull/484

2023-10-03 12:18 UTC, vishnuchalla requested changes
This extra configuration is not required as we can achieve the same in the rewamp logic: https://github.com/cloud-bulldozer/kube-burner/pull/484. Any thoughts? @rsevilla87

2023-10-03 14:04 UTC, closed without merging

2023-10-03 14:04 UTC, rsevilla87 commented
> This extra configuration is not required as we can achieve the same in the rewamp logic: #484. Any thoughts? @rsevilla87

honestly, I don't understand why are we duplicating some work.

2023-10-04 19:37 UTC, afcollins commented
I synced with Vishnu and this PR is still 1 of 3 changes required. #484 serves the purpose of fixing the end timestamp measurement.

This PR allows us to run an instant query at the start of a job boundary and is still required. I have some comments on the code I will leave in a review.

2023-10-04 19:52 UTC, afcollins commented on pkg/prometheus/prometheus.go
> +			if v, err = p.Client.Query(query, instantTimestamp); err != nil {
This is good. It allows me to make an instant query at the start of a job, and I can work with it.

Putting some feedback here in case it influences any implementation decisions:

Since I want to query a metric at the start AND end of a job, then I would need two separate metrics definitions: 1) `instant=true` and 2) `instant=true` and `instantJobStart=true`.

For how I am planning to use it, I think this could be a preferable outcome, because then I can query them as separate "columns" (if I am using benchmark-comparison), and then subtract the two columns from one another.  However, it does require I add two metrics definitions for each metric delta I want to capture.