Modifying churn logic to delete resources in namespaces
cloud-bulldozer/kube-burner pull request #492
Opened 2023-10-07 01:15 UTC by vishnuchalla

## Type of change

- [ ] Refactor
- [ ] New feature
- [ ] Bug fix
- [ ] Optimization
- [ ] Documentation Update

## Description

## Related Tickets & Documents

- Related Issue #
- Closes #

## Checklist before requesting a review

- [ ] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.

2023-10-19 13:49 UTC, rsevilla87 commented on pkg/burner/namespaces.go
> +			if obj.Namespaced && obj.labelSelector["kube-burner-namespace"] == namespace {
what's the goal of the label `kube-burner-namespace` ?

2023-10-19 22:17 UTC, vishnuchalla commented on pkg/burner/namespaces.go
> +			if obj.Namespaced && obj.labelSelector["kube-burner-namespace"] == namespace {
This label is to help us easily identify all the kube-burner specific resources within in a given namespace. Had to do this workaround because `client-go` only provides option to list a resource either using `Kind` or `GVR`, but doesn't provide us with a simple way to look at all the resources within a namespace and delete them.

2023-10-20 07:48 UTC, rsevilla87 commented
@afcollins this patch is not tested at high scale, I think it can lead to see longer durations while recreating namespaces, the flow is now:

- Delete all resources from namespace 1 (if we for example delete a deployment, we don't wait for all children pod to be pruned)
- Delete all resources from namespace N
- Once all the resources from the namespaces are pruned, delete the namespaces
- Wait for namespaces to be pruned

And the previous flow was:
- Delete all namespaces
- Wait for namespaces to be pruned

2023-10-23 15:34 UTC, vishnuchalla commented on pkg/burner/namespaces.go
> +			if obj.Namespaced && obj.labelSelector["kube-burner-namespace"] == namespace {
Yes, with the above statement `only provides option to list a resource either using Kind or GVR` I was referring to your suggestion, wherein we have to pass the object `GVR`, which turns out to be adding lot of code making it complicated instead simply adding the `namespace` label.

2023-10-23 16:28 UTC, rsevilla87 commented on pkg/burner/namespaces.go
> +			if obj.Namespaced && obj.labelSelector["kube-burner-namespace"] == namespace {
gotcha, so you're basically preventing to delete non namespaced objects. Then you can check for the Namespaced property:

```golang
		for _, obj := range objects {
            if ! obj.Namespaced{
                continue
           }
etc.
```

2023-10-27 14:55 UTC, vishnuchalla commented on pkg/burner/namespaces.go
> +			if obj.Namespaced && obj.labelSelector["kube-burner-namespace"] == namespace {
Removed the namespace and using `kube-burner-job` label to filter out all the objects in a namespace. Tested and verified the change.

2023-10-30 15:52 UTC, rsevilla87 commented on pkg/burner/namespaces.go
> +		if cleanupWait {
This conditional is always true

2023-10-30 15:53 UTC, rsevilla87 commented
Hey @vishnuchalla, I've tested the latest changes locally and is still not working well

```shell
time="2023-10-30 16:48:18" level=info msg="Running job cluster-density-v2" file="create.go:112"
time="2023-10-30 16:48:19" level=info msg="1/10 iterations completed" file="create.go:130"
time="2023-10-30 16:48:21" level=info msg="2/10 iterations completed" file="create.go:130"
time="2023-10-30 16:48:23" level=info msg="3/10 iterations completed" file="create.go:130"
time="2023-10-30 16:48:24" level=info msg="4/10 iterations completed" file="create.go:130"
time="2023-10-30 16:48:26" level=info msg="5/10 iterations completed" file="create.go:130"
time="2023-10-30 16:48:28" level=info msg="6/10 iterations completed" file="create.go:130"
time="2023-10-30 16:48:30" level=info msg="7/10 iterations completed" file="create.go:130"
time="2023-10-30 16:48:32" level=info msg="8/10 iterations completed" file="create.go:130"
time="2023-10-30 16:48:34" level=info msg="9/10 iterations completed" file="create.go:130"
time="2023-10-30 16:48:36" level=info msg="Waiting up to 4h0m0s for actions to be completed" file="create.go:171"
time="2023-10-30 16:48:42" level=info msg="Actions in namespace cluster-density-v2-0 completed" file="waiters.go:76"
time="2023-10-30 16:48:44" level=info msg="Actions in namespace cluster-density-v2-1 completed" file="waiters.go:76"
time="2023-10-30 16:48:46" level=info msg="Actions in namespace cluster-density-v2-2 completed" file="waiters.go:76"
time="2023-10-30 16:48:46" level=info msg="Actions in namespace cluster-density-v2-3 completed" file="waiters.go:76"
time="2023-10-30 16:48:48" level=info msg="Actions in namespace cluster-density-v2-4 completed" file="waiters.go:76"
time="2023-10-30 16:48:52" level=info msg="Actions in namespace cluster-density-v2-6 completed" file="waiters.go:76"
time="2023-10-30 16:48:52" level=info msg="Actions in namespace cluster-density-v2-7 completed" file="waiters.go:76"
time="2023-10-30 16:48:52" level=info msg="Actions in namespace cluster-density-v2-5 completed" file="waiters.go:76"
time="2023-10-30 16:48:57" level=info msg="Actions in namespace cluster-density-v2-8 completed" file="waiters.go:76"
time="2023-10-30 16:48:58" level=info msg="Actions in namespace cluster-density-v2-9 completed" file="waiters.go:76"
time="2023-10-30 16:48:58" level=info msg="Verifying created objects" file="utils.go:86"
time="2023-10-30 16:48:58" level=info msg="imagestreams found: 10 Expected: 10" file="utils.go:119"
time="2023-10-30 16:48:59" level=info msg="builds found: 10 Expected: 10" file="utils.go:119"
time="2023-10-30 16:48:59" level=info msg="deployments found: 30 Expected: 30" file="utils.go:119"
time="2023-10-30 16:48:59" level=info msg="deployments found: 20 Expected: 20" file="utils.go:119"
time="2023-10-30 16:48:59" level=info msg="services found: 50 Expected: 50" file="utils.go:119"
time="2023-10-30 16:48:59" level=info msg="routes found: 20 Expected: 20" file="utils.go:119"
time="2023-10-30 16:49:00" level=info msg="secrets found: 100 Expected: 100" file="utils.go:119"
time="2023-10-30 16:49:00" level=info msg="configmaps found: 100 Expected: 100" file="utils.go:119"
time="2023-10-30 16:49:00" level=info msg="networkpolicies found: 10 Expected: 10" file="utils.go:119"
time="2023-10-30 16:49:00" level=info msg="networkpolicies found: 10 Expected: 10" file="utils.go:119"
time="2023-10-30 16:49:01" level=info msg="networkpolicies found: 10 Expected: 10" file="utils.go:119"
time="2023-10-30 16:49:01" level=info msg="Deleting resources in namespace cluster-density-v2-0" file="namespaces.go:85"
time="2023-10-30 16:49:02" level=error msg="Error deleting client-1 in namespace cluster-density-v2-0: deployments.apps \"client-1\" not found" file="namespaces.go:98"
time="2023-10-30 16:49:02" level=error msg="Error deleting server-2 in namespace cluster-density-v2-0: deployments.apps \"server-2\" not found" file="namespaces.go:98"
time="2023-10-30 16:49:02" level=error msg="Error deleting client-2 in namespace cluster-density-v2-0: deployments.apps \"client-2\" not found" file="namespaces.go:98"
time="2023-10-30 16:49:02" level=error msg="Error deleting server-1 in namespace cluster-density-v2-0: deployments.apps \"server-1\" not found" file="namespaces.go:98"
time="2023-10-30 16:49:02" level=error msg="Error deleting server-3 in namespace cluster-density-v2-0: deployments.apps \"server-3\" not found" file="namespaces.go:98"
time="2023-10-30 16:49:03" level=error msg="Error deleting deny-all in namespace cluster-density-v2-0: networkpolicies.networking.k8s.io \"deny-all\" not found" file="namespaces.go:98"
time="2023-10-30 16:49:03" level=error msg="Error deleting allow-from-clients-1 in namespace cluster-density-v2-0: networkpolicies.networking.k8s.io \"allow-from-clients-1\" not found" file="namespaces.go:98"
time="2023-10-30 16:49:03" level=error msg="Error deleting allow-from-openshift-ingress in namespace cluster-density-v2-0: networkpolicies.networking.k8s.io \"allow-from-openshift-ingress\" not found" file="namespaces.go:98"
time="2023-10-30 16:49:05" level=info msg="Deleting resources in namespace cluster-density-v2-0 completed" file="namespaces.go:107"
time="2023-10-30 16:49:05" level=info msg="Deleting namespaces with label churndelete=delete" file="namespaces.go:64"
etc.
```

As you can see, kube-burner crashes when deleting some deployments and networkpolicies, this is due to a race condition that happens because there're multiple objects of the same type in the objects list, so kube-burner tries to deleteall the  deployments/networkpolicies within the same namespace more than one time, and the second time crashes, because it has been deleted in the background by the previous goroutine. The code I shared with you the last week contemplated this:

```diff
func CleanupNamespaceResourcesUsingGVR(ctx context.Context, objects []object, namespacesToDelete []string, jobName string) {
+	deletedKinds := []string{} // There could be jobs with multiple objects of the same kind
 	for _, namespace := range namespacesToDelete {
 		log.Infof("Deleting resources in namespace %s", namespace)
-		l := metav1.ListOptions{LabelSelector: fmt.Sprintf("kube-burner-namespace=%s", namespace)}
+	object:
 		for _, obj := range objects {
-			if obj.Namespaced && obj.labelSelector["kube-burner-namespace"] == namespace {
+			for _, kind := range deletedKinds {
+				if obj.kind == kind {
+					continue object
+				}
+			}
+			deletedKinds = append(deletedKinds, obj.kind)
```

2023-10-30 18:06 UTC, vishnuchalla commented on pkg/burner/namespaces.go
> +		if cleanupWait {
Removed this flag as it not required as of now.

2023-10-30 18:30 UTC, vishnuchalla commented
> Hey @vishnuchalla, I've tested the latest changes locally and is still not working well
> 
> ```shell
> time="2023-10-30 16:48:18" level=info msg="Running job cluster-density-v2" file="create.go:112"
> time="2023-10-30 16:48:19" level=info msg="1/10 iterations completed" file="create.go:130"
> time="2023-10-30 16:48:21" level=info msg="2/10 iterations completed" file="create.go:130"
> time="2023-10-30 16:48:23" level=info msg="3/10 iterations completed" file="create.go:130"
> time="2023-10-30 16:48:24" level=info msg="4/10 iterations completed" file="create.go:130"
> time="2023-10-30 16:48:26" level=info msg="5/10 iterations completed" file="create.go:130"
> time="2023-10-30 16:48:28" level=info msg="6/10 iterations completed" file="create.go:130"
> time="2023-10-30 16:48:30" level=info msg="7/10 iterations completed" file="create.go:130"
> time="2023-10-30 16:48:32" level=info msg="8/10 iterations completed" file="create.go:130"
> time="2023-10-30 16:48:34" level=info msg="9/10 iterations completed" file="create.go:130"
> time="2023-10-30 16:48:36" level=info msg="Waiting up to 4h0m0s for actions to be completed" file="create.go:171"
> time="2023-10-30 16:48:42" level=info msg="Actions in namespace cluster-density-v2-0 completed" file="waiters.go:76"
> time="2023-10-30 16:48:44" level=info msg="Actions in namespace cluster-density-v2-1 completed" file="waiters.go:76"
> time="2023-10-30 16:48:46" level=info msg="Actions in namespace cluster-density-v2-2 completed" file="waiters.go:76"
> time="2023-10-30 16:48:46" level=info msg="Actions in namespace cluster-density-v2-3 completed" file="waiters.go:76"
> time="2023-10-30 16:48:48" level=info msg="Actions in namespace cluster-density-v2-4 completed" file="waiters.go:76"
> time="2023-10-30 16:48:52" level=info msg="Actions in namespace cluster-density-v2-6 completed" file="waiters.go:76"
> time="2023-10-30 16:48:52" level=info msg="Actions in namespace cluster-density-v2-7 completed" file="waiters.go:76"
> time="2023-10-30 16:48:52" level=info msg="Actions in namespace cluster-density-v2-5 completed" file="waiters.go:76"
> time="2023-10-30 16:48:57" level=info msg="Actions in namespace cluster-density-v2-8 completed" file="waiters.go:76"
> time="2023-10-30 16:48:58" level=info msg="Actions in namespace cluster-density-v2-9 completed" file="waiters.go:76"
> time="2023-10-30 16:48:58" level=info msg="Verifying created objects" file="utils.go:86"
> time="2023-10-30 16:48:58" level=info msg="imagestreams found: 10 Expected: 10" file="utils.go:119"
> time="2023-10-30 16:48:59" level=info msg="builds found: 10 Expected: 10" file="utils.go:119"
> time="2023-10-30 16:48:59" level=info msg="deployments found: 30 Expected: 30" file="utils.go:119"
> time="2023-10-30 16:48:59" level=info msg="deployments found: 20 Expected: 20" file="utils.go:119"
> time="2023-10-30 16:48:59" level=info msg="services found: 50 Expected: 50" file="utils.go:119"
> time="2023-10-30 16:48:59" level=info msg="routes found: 20 Expected: 20" file="utils.go:119"
> time="2023-10-30 16:49:00" level=info msg="secrets found: 100 Expected: 100" file="utils.go:119"
> time="2023-10-30 16:49:00" level=info msg="configmaps found: 100 Expected: 100" file="utils.go:119"
> time="2023-10-30 16:49:00" level=info msg="networkpolicies found: 10 Expected: 10" file="utils.go:119"
> time="2023-10-30 16:49:00" level=info msg="networkpolicies found: 10 Expected: 10" file="utils.go:119"
> time="2023-10-30 16:49:01" level=info msg="networkpolicies found: 10 Expected: 10" file="utils.go:119"
> time="2023-10-30 16:49:01" level=info msg="Deleting resources in namespace cluster-density-v2-0" file="namespaces.go:85"
> time="2023-10-30 16:49:02" level=error msg="Error deleting client-1 in namespace cluster-density-v2-0: deployments.apps \"client-1\" not found" file="namespaces.go:98"
> time="2023-10-30 16:49:02" level=error msg="Error deleting server-2 in namespace cluster-density-v2-0: deployments.apps \"server-2\" not found" file="namespaces.go:98"
> time="2023-10-30 16:49:02" level=error msg="Error deleting client-2 in namespace cluster-density-v2-0: deployments.apps \"client-2\" not found" file="namespaces.go:98"
> time="2023-10-30 16:49:02" level=error msg="Error deleting server-1 in namespace cluster-density-v2-0: deployments.apps \"server-1\" not found" file="namespaces.go:98"
> time="2023-10-30 16:49:02" level=error msg="Error deleting server-3 in namespace cluster-density-v2-0: deployments.apps \"server-3\" not found" file="namespaces.go:98"
> time="2023-10-30 16:49:03" level=error msg="Error deleting deny-all in namespace cluster-density-v2-0: networkpolicies.networking.k8s.io \"deny-all\" not found" file="namespaces.go:98"
> time="2023-10-30 16:49:03" level=error msg="Error deleting allow-from-clients-1 in namespace cluster-density-v2-0: networkpolicies.networking.k8s.io \"allow-from-clients-1\" not found" file="namespaces.go:98"
> time="2023-10-30 16:49:03" level=error msg="Error deleting allow-from-openshift-ingress in namespace cluster-density-v2-0: networkpolicies.networking.k8s.io \"allow-from-openshift-ingress\" not found" file="namespaces.go:98"
> time="2023-10-30 16:49:05" level=info msg="Deleting resources in namespace cluster-density-v2-0 completed" file="namespaces.go:107"
> time="2023-10-30 16:49:05" level=info msg="Deleting namespaces with label churndelete=delete" file="namespaces.go:64"
> etc.
> ```
> 
> As you can see, kube-burner crashes when deleting some deployments and networkpolicies, this is due to a race condition that happens because there're multiple objects of the same type in the objects list, so kube-burner tries to deleteall the deployments/networkpolicies within the same namespace more than one time, and the second time crashes, because it has been deleted in the background by the previous goroutine. The code I shared with you last week contemplated this:
> 
> ```diff
> func CleanupNamespaceResourcesUsingGVR(ctx context.Context, objects []object, namespacesToDelete []string, jobName string) {
> +	deletedKinds := []string{} // There could be jobs with multiple objects of the same kind
>  	for _, namespace := range namespacesToDelete {
>  		log.Infof("Deleting resources in namespace %s", namespace)
> -		l := metav1.ListOptions{LabelSelector: fmt.Sprintf("kube-burner-namespace=%s", namespace)}
> +	object:
>  		for _, obj := range objects {
> -			if obj.Namespaced && obj.labelSelector["kube-burner-namespace"] == namespace {
> +			for _, kind := range deletedKinds {
> +				if obj.kind == kind {
> +					continue object
> +				}
> +			}
> +			deletedKinds = append(deletedKinds, obj.kind)
> ```

Thanks for bringing this up. Added logic to check for the duplicates and skip them.

2023-11-07 08:53 UTC, rsevilla87 requested changes
To make this change less aggressive I think you could add a new config parameter `churnDeleteStrategy` that would allow the user to decide if he wants to delete the entire namespaces (default logic) or resources in namespaces (new logic), wdyt?

2023-11-11 02:53 UTC, vishnuchalla commented
> To make this change less aggressive I think you could add a new config parameter `churnDeleteStrategy` that would allow the user to decide if he wants to delete the entire namespaces (default logic) or resources in namespaces (new logic), wdyt?

Acknowledged. Introduced a flag for this new logic

2023-11-17 14:15 UTC, rsevilla87 commented on pkg/workloads/cluster-density.go
> +			fmt.Println(churnDeletionStrategy)
Remove this line

2023-11-17 14:34 UTC, vishnuchalla commented on pkg/workloads/cluster-density.go
> +			fmt.Println(churnDeletionStrategy)
Done.

2023-11-17 17:19 UTC, rsevilla87 approved these changes
lgtm

2023-11-17 17:19 UTC, merged