Deprecate cluster-density
cloud-bulldozer/kube-burner pull request #510
Opened 2023-11-10 10:12 UTC by rsevilla87

## Type of change

- [ ] Refactor
- [ ] New feature
- [ ] Bug fix
- [x] Optimization
- [x] Documentation Update

## Description

Deprecating the original cluster-density workload. We should use cluster-density-v2 in all our tests, this workload is more relevant and complete.

Changes will be applied in the next kube-burner major version

cc: @paigerube14 @jtaleric @dry923 @afcollins @svetsa-rh @krishvoor 

## Related Tickets & Documents

- Related Issue #
- Closes #

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.

2023-11-10 13:56 UTC, jtaleric approved these changes
lgtm

2023-11-10 13:58 UTC, krishvoor approved these changes
/lgtm

2023-11-10 14:29 UTC, vishnuchalla approved these changes

2023-11-10 14:32 UTC, paigerube14 commented
/lgtm

2023-11-10 15:18 UTC, afcollins approved these changes
LGTM!

2023-11-11 07:38 UTC, smalleni requested changes
This is total removal, not deprecation so I don't believe the help should include this any more.

2023-11-11 07:38 UTC, smalleni commented on docs/ocp.md
> +  cluster-density    Runs cluster-density workload. Deprecated
This is total removal, not deprecation so I don't believe the help should include this any more.

2023-11-13 11:33 UTC, rsevilla87 commented on docs/ocp.md
> +  cluster-density    Runs cluster-density workload. Deprecated
fixed

2023-11-15 10:00 UTC, merged